export const gallery = [
  { src: "/images/gallery/g01.jpg", title: "Dekor LED" },
  { src: "/images/gallery/g02.jpg", title: "Dekor LED" },
  { src: "/images/gallery/g03.jpg", title: "Térvilágítás csere" },
  { src: "/images/gallery/g04.jpg", title: "Alapszerelés" },
  { src: "/images/gallery/g05.jpg", title: "Alapszerelés" },
  { src: "/images/gallery/g06.jpg", title: "Elosztó behúzás" },
  { src: "/images/gallery/g07.jpg", title: "Fürdő LED világítás" },
  { src: "/images/gallery/g08.jpg", title: "Nappali dekor LED" },
  { src: "/images/gallery/g09.jpg", title: "LED driver elosztó" },
  { src: "/images/gallery/g10.jpg", title: "Nappali világítás" },
  { src: "/images/gallery/g11.jpg", title: "LED mátrix fal szekvenciális vezérlő (TV2)" },
  { src: "/images/gallery/g12.jpg", title: "Egyedi gépgyártás (folyamatban)" },
  { src: "/images/gallery/g13.jpg", title: "Albérletek" },
  { src: "/images/gallery/g14.jpg", title: "Alapcsövezés" },
  { src: "/images/gallery/g15.jpg", title: "Födém külső szerelés" },
  { src: "/images/gallery/g16.jpg", title: "Térvilágítás csere" },
  { src: "/images/gallery/g17.jpg", title: "Fő elosztó / LED táp szekrény" },
  { src: "/images/gallery/g18.jpg", title: "Elosztófal" },
  { src: "/images/gallery/g19.jpg", title: "Fő elosztó / LED driver" },
  { src: "/images/gallery/g20.jpg", title: "Integrált LED" },
  { src: "/images/gallery/g21.jpg", title: "Energiaelosztó almérőkkel" },
  { src: "/images/gallery/g22.jpg", title: "Hűtőház világítás korszerűsítés" },
  { src: "/images/gallery/g23.jpg", title: "Mini elosztó családi ház" },
  { src: "/images/gallery/g24.jpg", title: "Internet légkábelezés" },
  { src: "/images/gallery/g25.jpg", title: "Földkábeles nyomvonal" },
  { src: "/images/gallery/g26.jpg", title: "Parkoló LED Street lámpa" },
  { src: "/images/gallery/g27.jpg", title: "Szolár LED lámpák" },
  { src: "/images/gallery/g28.jpg", title: "MakeUp szalon" },
  { src: "/images/gallery/g29.jpg", title: "Kristály lámpák" },
  { src: "/images/gallery/g30.jpg", title: "Dekor LED" },
  { src: "/images/gallery/g31.jpg", title: "Garancia védelem" },
  { src: "/images/gallery/g32.jpg", title: "Fő elosztó" },
  { src: "/images/gallery/g33.jpg", title: "MakeUp szalon folyamatban" },
  { src: "/images/gallery/g34.jpg", title: "Családi ház" },
  { src: "/images/gallery/g35.jpg", title: "Elektromos kapuk" },
  { src: "/images/gallery/g36.jpg", title: "Alelosztó" },
  { src: "/images/gallery/g37.jpg", title: "Hangulatvilágítások" },
  { src: "/images/gallery/g38.jpg", title: "Future LED dekor" },
  { src: "/images/gallery/g39.jpg", title: "Optical Kft. elektromos kivitelezés" },
  { src: "/images/gallery/g40.jpg", title: "Ipari csatlakozó táblák" },
  { src: "/images/gallery/g41.jpg", title: "Modern térmegvilágítás" },
  { src: "/images/gallery/g42.jpg", title: "Komplett elektromos kivitelezés" },
  { src: "/images/gallery/g43.jpg", title: "Földkábelezés" },
  { src: "/images/gallery/g44.jpg", title: "Ipari csarnokok komplett kivitelezés" },
  { src: "/images/gallery/g45.jpg", title: "DPD Hungary Kft." },
  { src: "/images/gallery/g46.jpg", title: "Elosztó kábelezés" },
  { src: "/images/gallery/g47.jpg", title: "Sorközmegvilágítás" },
  { src: "/images/gallery/g48.jpg", title: "Raktárvilágítás" },
  { src: "/images/gallery/g49.jpg", title: "Kábeltálca szerelés" },
  { src: "/images/gallery/g50.jpg", title: "Kábeltálca szerelés" },
  { src: "/images/gallery/g51.jpg", title: "Családi ház elosztófal" },
  { src: "/images/gallery/g52.jpg", title: "Ipari csarnokok" },
  { src: "/images/gallery/g53.jpg", title: "Felvonulás" },
  { src: "/images/gallery/g54.jpg", title: "LED világítás" },
  { src: "/images/gallery/g55.jpg", title: "LED világítás" },
  { src: "/images/gallery/g56.jpg", title: "Dekor LED világítás" },
  { src: "/images/gallery/g57.jpg", title: "Exkluzív terek világítása" },
  { src: "/images/gallery/g58.jpg", title: "Exkluzív világítások" },
  { src: "/images/gallery/g59.jpg", title: "Exkluzív világítások" },
  { src: "/images/gallery/g60.jpg", title: "Ipari kivitelezés" },
  { src: "/images/gallery/g61.jpg", title: "Helyszíni munkavégzés" },
] as const;
